# Generated by Django 4.0.6 on 2022-08-02 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='type',
            new_name='types',
        ),
    ]
